---
name: Checks

# Trigger
on: [push]

jobs:
  test-lint:
    name: Test & Lint
    runs-on: ubuntu-20.04
    steps:
      # Login to Docker
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      # Checks out the code in the job runner
      - name: Checkout
        uses: actions/checkout@v2
      # Run the tests with django test suite
      - name: Test
        run: docker-compose run --rm app sh -c "python manage.py wait_for_db && python manage.py test"
      # Lint the code with flake8
      - name: Lint
        run: docker-compose run --rm app sh -c "flake8"
